name: Backup and Transfer

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      SOURCE_DIR: /var/www/html
      LOCAL_BACKUP_DIR: /tmp/backups
      REMOTE_USER: backupuser
      REMOTE_HOST: 192.168.1.100
      REMOTE_DIR: /home/backupuser/backups

    steps:
      - name: Set up timestamp
        id: vars
        run: echo "timestamp=$(date +%Y%m%d_%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Create local backup directory
        run: mkdir -p $LOCAL_BACKUP_DIR

      - name: Create backup archive
        run: |
          BACKUP_FILE="backup_${{ steps.vars.outputs.timestamp }}.tar.gz"
          tar -czf "$LOCAL_BACKUP_DIR/$BACKUP_FILE" -C "$SOURCE_DIR" .
          echo "backup_file=$BACKUP_FILE" >> $GITHUB_ENV

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Transfer backup to remote host
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "mkdir -p $REMOTE_DIR"
          scp -o StrictHostKeyChecking=no "$LOCAL_BACKUP_DIR/$backup_file" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/"

      - name: Verify remote backup
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "ls -lh $REMOTE_DIR/$backup_file"
