name: Backup and Store MySQL Databases Locally

on:
  workflow_dispatch:

jobs:
  backup-and-store:
    runs-on: self-hosted  # or use ubuntu-latest depending on your preference

    env:
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Set up MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Dump all databases individually
        run: |
          mkdir -p dumps
          DBS=$(mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|mysql|sys)")
          for DB in $DBS; do
            echo "Dumping $DB"
            mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $DB > dumps/${DB}.sql
          done

      - name: Create tar.gz with current date and time
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          TAR_NAME="mysql_backup_$TIMESTAMP.tar.gz"
          tar -czf "$TAR_NAME" -C dumps .
          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV

      - name: Store backup locally
        run: |
          mkdir -p ~/mysql_backups
          mv "$TAR_NAME" ~/mysql_backups/
          echo "Backup stored locally at ~/mysql_backups/$TAR_NAME"
