name: Backup and Upload MySQL Databases

on:
  workflow_dispatch:

jobs:
  backup-and-upload:
    runs-on: ubuntu-latest
    env:
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Set up SSH key and MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client openssh-client
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into the server and dump all databases
        id: dump_and_archive
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" bash << EOF
            set -e
            mkdir -p dumps
            DBS=\$(mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|mysql|sys)")
            for DB in \$DBS; do
              echo "Dumping \$DB"
