name: Backup and Upload MySQL Databases

on:
  workflow_dispatch:

jobs:
  backup-and-upload:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Set up SSH key and MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client openssh-client
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into the server and dump all databases
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 'bash -s' <<'EOF'
            set -e
            mkdir -p dumps
            DBS=$(mysql -u root -p"${MYSQL_PASSWORD}" -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema|mysql|sys)")
            for DB in $DBS; do
              echo "Dumping $DB"
              mysqldump -u root -p"${MYSQL_PASSWORD}" "$DB" > dumps/"${DB}.sql"
            done
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
            TAR_NAME="mysql_backup_${TIMESTAMP}.tar.gz"
            tar -czf "$TAR_NAME" -C dumps .
            echo "$TAR_NAME" > /tmp/backup_name.txt
          EOF

      - name: Retrieve tarball name from remote server
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 'cat /tmp/backup_name.txt' > backup_name.txt
          TAR_NAME=$(cat backup_name.txt)
          echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV

      - name: Clean up old backups on remote server (older than 2 days)
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" \
            'find /var/www/html/database_backup/ -name "mysql_backup_*.tar.gz" -type f -mtime +2 -exec rm -f {} \;'

      - name: Upload tarball to remote server via SCP
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST:$TAR_NAME" .
          scp -i private_key.pem -o StrictHostKeyChecking=no "$TAR_NAME" "$SSH_USER@$SSH_HOST:/var/www/html/database_backup/"
