- name: Validate Required Secrets
  run: |
    missing=0

    if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
      echo "❌ Missing SSH_PRIVATE_KEY"
      missing=1
    fi
    if [ -z "${{ secrets.REMOTE_HOST }}" ]; then
      echo "❌ Missing REMOTE_HOST"
      missing=1
    fi
    if [ -z "${{ secrets.REMOTE_USER }}" ]; then
      echo "❌ Missing REMOTE_USER"
      missing=1
    fi
    if [ -z "${{ secrets.PROJECT_PATH }}" ]; then
      echo "❌ Missing PROJECT_PATH"
      missing=1
    fi
    if [ -z "${{ secrets.BACKUP_SERVER }}" ]; then
      echo "❌ Missing BACKUP_SERVER"
      missing=1
    fi
    if [ -z "${{ secrets.BACKUP_USER }}" ]; then
      echo "❌ Missing BACKUP_USER"
      missing=1
    fi
    if [ -z "${{ secrets.BACKUP_PATH }}" ]; then
      echo "❌ Missing BACKUP_PATH"
      missing=1
    fi

    if [ "$missing" -eq 1 ]; then
      echo "🚫 One or more required secrets are missing. Failing the workflow."
      exit 1
    fi
