name: Magento CI with LXC

on:
  push:
    branches:
      - main

jobs:
  setup-lxc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LXC container with SSH
        uses: lkiesow/setup-lxc-container@v1
        id: lxc
        with:
          dist: ubuntu
          release: focal
          name: magento-container
          configure-ssh: true

      - name: Display container IP address
        run: |
          echo "Container IP address: ${{ steps.lxc.outputs.ip }}"

      - name: Test SSH access
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ steps.lxc.outputs.ip }} echo "SSH access successful"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
