name: Magento CI with LXC

on:
  push:
    branches:
      - main

jobs:
  setup-lxc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LXD
        uses: canonical/setup-lxd@v0.1.1
        id: lxd
        with:
          channel: latest/stable

      - name: Launch LXC container
        run: |
          sudo lxd waitready
          sudo lxd init --auto
          sudo lxc launch ubuntu:20.04 magento-container

            - name: Configure DNS for LXD container
        run: |
          sudo lxc exec magento-container -- bash -c "
            # Check if /etc/resolv.conf exists
            if [ ! -f /etc/resolv.conf ]; then
              # Create /etc/resolv.conf with Google's DNS
              echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf > /dev/null
              echo 'nameserver 8.8.4.4' | sudo tee -a /etc/resolv.conf > /dev/null
            fi
            # Verify DNS resolution
            cat /etc/resolv.conf
          "

      - name: Install Magento
        run: |
          sudo lxc exec magento-container -- bash -c "
            apt-get update &&
            apt-get install -y curl unzip &&
            curl -sS https://getcomposer.org/installer | php &&
            mv composer.phar /usr/local/bin/composer &&
            composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/magento
          "

      - name: Set up Magento
        run: |
          sudo lxc exec magento
