name: Magento CI with LXD

on:
  push:
    branches:
      - main

jobs:
  setup-lxd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable

      - name: Launch LXD container
        run: |
          sudo lxd init --auto
          lxc launch ubuntu:20.04 magento-container

      - name: Install Magento
        run: |
          sudo lxc exec magento-container -- bash -c "
            apt-get update &&
            apt-get install -y curl unzip &&
            curl -sS https://getcomposer.org/installer | php &&
            mv composer.phar /usr/local/bin/composer &&
            composer create-project --repository=https://repo.magento.com/ magento/project-community-edition /var/www/magento
          "

      - name: Set up Magento
        run: |
          sudo lxc exec magento-container -- bash -c "
            cd /var/www/magento &&
            php bin/magento setup:install \
              --base-url=http://localhost/magento \
              --db-host=localhost \
              --db-name=magento \
              --db-user=magento \
              --db-password=magento123 \
              --admin-firstname=Admin \
              --admin-lastname=User \
              --admin-email=admin@example.com \
              --admin-user=admin \
              --admin-password=admin123 \
              --language=en_US \
              --currency=USD \
              --timezone=America/Chicago \
              --use-rewrites=1
          "

      - name: Set permissions
        run: |
          sudo lxc exec magento-container -- bash -c "
            chown -R www-data:www-data /var/www/magento &&
            chmod -R 755 /var/www/magento
          "

      - name: Output SSH access details
        run: |
          echo "SSH into the container using the following details:"
          echo "Host: '${{ steps.lxd.outputs.ip }}'"
          echo "User: root"
          echo "Port: 22"
